### ISSUE TITLE
请问什么时候可以加一个还原按钮，还原到原始样子

### ISSUE THREAD

**Issue by IT-Rafi** [AnaniZhu/vue-img-viewer#1]
请问什么时候可以加一个还原按钮，还原到原始样子

**Comment by AnaniZhu** [comment]
抱歉现在才看到，最新的 **v1.2.0** 应该满足你的要求

1. 添加三个对外方法 rotate, zoom, reset
2. 底部操作栏新增_重置_按钮
3. 可通过 slot = "operate" 自定义底部操作栏

**Comment by IT-Rafi** [comment]
图片要是太大能加个加载状态么？或者提供个对外的方法

**Comment by AnaniZhu** [comment]
> 图片要是太大能加个加载状态么？或者提供个对外的方法

之前测试的时候缩略图和预览图用的是一个，忽略了大图加载速度的问题。。。

v1.3.1 新增了 loading 过渡，同时支持 loading slot. 详情可见 [slot](https://github.com/AnaniZhu/vue-img-viewer#slots)

**Comment by IT-Rafi** [comment]
可以了
