### ISSUE TITLE
图标显示错误

### ISSUE THREAD

**Issue by mercer08** [AnaniZhu/vue-img-viewer#7]

**Comment by AnaniZhu** [comment]
我刚试了下是正常的，有详细描述或截图吗？

**Comment by mercer08** [comment]
解决了，应该是定义的iconfont字体，与已有的element ui的字体冲突了，导致显示了其他的图标，建议用svg图标来避免冲突

**Comment by mercer08** [comment]
![image](https://user-images.githubusercontent.com/12872293/87152406-3a079c80-c2e8-11ea-8a5d-7906c1d0a7f2.png)
![image](https://user-images.githubusercontent.com/12872293/87152985-47715680-c2e9-11ea-81f2-042f3c36995a.png)
![image](https://user-images.githubusercontent.com/12872293/87153026-58ba6300-c2e9-11ea-8f1c-061fb64753e5.png)
比较了一下，在我的项目里viewer组件打开的时候会多加载一个dataUrl的字体base64文件，具体原因还没找到

**Comment by mercer08** [comment]
下面是多出来的内容，我目前解决方案是fork一遍后，用svg替换了字体图标，显示正常
`Request URL: data:application/x-font-woff;charset=utf-8;base64,d09GRgABAAAAABzAAAsAAAAAOUAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAABHU1VCAAABCAAAADMAAABCsP6z7U9TLzIAAAE8AAAARAAAAFZW7kqeY21hcAAAAYAAAAG2AAAEdkOLQ8ZnbHlmAAADOAAAFjoAAC3cKIc7KGhlYWQAABl0AAAALgAAADYRjbvlaGhlYQAAGaQAAAAcAAAAJAfeA7BobXR4AAAZwAAAABQAAAC8u+kAAGxvY2EAABnUAAAAYAAAAGD1EwEgbWF4cAAAGjQAAAAfAAAAIAFTASduYW1lAAAaVAAAAUUAAAJtPlT+fXBvc3QAABucAAABJAAAAYmG9s52eJxjYGRgYOBikGPQYWB0cfMJYeBgYGGAAJAMY05meiJQDMoDyrGAaQ4gZoOIAgCKIwNPAHicY2BkYWCcwMDKwMHUyXSGgYGhH0IzvmYwYuRgYGBiYGVmwAoC0lxTGBwYKl6sYW7438AQw9zA0AAUZgTJAQDgJQwjeJzF1ElOG0EYxfF/g7HjmMxzjBOceURRJCRWWUTZgUBkIEEEi8wTB0BwAk7ADVhxriffgrzq5w07NlG69JPcra/dVfW9bmACGLcn1oCxF1T+RTXnq1V9fZyT9fVGNenzB0y77gRbaqiltjrqqa9ZLWhJq1rTQJva0a72hvvDg8ND31Eqm3Vlt66c16KWXbmuDW0fqTzOUXkGZTyqx0w9nvGclx6v+MhgNErlKU7z2Ct4SsszbnsdY5zhLOe5wEXOcYnLXOEq17hOlyl63OCm/2+aPre4zR3uco/7ftpDP2uCpveiQQfvQ9U85nz/wVH9v0cfPUoeGJsbnc3Y1oinqEa4C6gZ7gdqhTuD2lHSp064W6gblNqpcAdRLyj39aOkU7Ph/qL5cKfRQrjnaDHcfbQUzgFaDicCvQ5nA70JpwS9DecFvQsnB62EM4Teh9OEPoRzhVaDsqa1oKxpPShrGoTzhzbCSUSfouytPofTib4EZQ++hhOLvoWzi76HU4x+hPOMfoaTjX6FM45+h9OO/oRzjzbDbwDajvLV0E5Qersb5UuivShfk+F++J1heBBM/gXfUq6NAAB4nL06CXAc1ZX/dU8fc0/3TPefSzPd03NIlqyR5rQt25IsbPkIlpCNTTAYs4bCgcKASUIA18Z2DsKRFAHlImbLITjLuoCQiwSTQyRLNhwhx4YlB2CR7G5SbJbdLJsltWiafb9nZMuyJdkhtT0z//2733v/nd1DBELeeoX/Jh8lYdJOesk5ZJQQEDshE+DawCxUurlO0ExBo5EAX7AKpmRluvkVQDNiRC/VKnkqSmIQApCCslmqFbq5AlQrK7k+KOltALFEfJOaS6r8neCJFlIfstdz94GWtpLBlYvtdV39kZIRlm/wqWpMVe+QRUGQOc4VDMDVVHcLbo9o3y8E49o30x1cGnyxQvwd7/QbCfXSj1R2t+WoG2DfPggnjMDf9itxBb9743pYjUkhvxyN+61sBG74Z2807GvL/4bgxSGtE/wWfoC4iESIYComlawqf35jCzz/vPH0AL/vef0Zwsbe2sfjhwhEJnHSRixSJYPIlyouUQpaH1SKkLfMjKgpEZ3RXeWpFcZBrQyFPLImDRLjTz/UKgVqMV4hQ5Bb3J024SYnJ0PCpCDaoYCqBriJgDp55MhEYwAmJ+0r3y/43cJ73iO4/cI+QfjjhOR2S6zg7pycMngyOSniUjUwNcDW8keONAg/MWkffD9bgMtw8T5XwHWzO+DGLyHiDFoo0mKQElk5TUn57ZHxZxNxdiQQhdHgIkhDkMSQBotkyWKyjKwnG8kY+Suyhxwgd5GD5BB5iBAtBdRcCXWlGwpmACShWnFIbAPBSjnIZ8QZtYiIg/lKDanXJTNfELUWJyoFMVfWLPbj2T4a7mni3tVukGa1CwuMh6dxUaqmZuZm3hKyCX5fIgsIpxjkJ5AvyEtuYgCytSx+7f7pGneJGrCJw20sDZuobqFZF9yN7oEBfgCvRms3rgXPsp2b7uJJg3A78Ib72A0By4HWxIkmnJxgAxOHEgy1bKIFsC+pqt0QlNxs2C0FjxmGAZO44FBzHYJ+BEazhWDwpNb7T2rZnwPSbLxFDONQc3fUXibTEygPfrRaBsoDAYe900cPTk1Q8lYAmJWqVyn2cfvs1mY8g/YE1oDYJKh01GpjNZgAFLHpg3BYAgNvsZk77P8VAWfUOiYMMN4igDLJcPgKv5c/F3FIkDQpNHFgitTEodBqlZstiVYLFpPNcpW71+6MmhnK3RQ14diM+k2XHzsmgxF7iO/BcuqNmAEIucummi3Tadx0+ctPHXsIZ8tomxgON8zAoUz6yQay9WRcqifhUj0JF8FkesD0I6ILTll2epgIN1dX8lBmPegRcJT7lN0VNc0ow/fYiepNl718TEL0HmwchBfdPp/bzmIJ/+IA94yuZt1O/JbVWXFmpH7Vp/r9qm+rL+zD737wqT5wiguxF8eaNvuL/E/49Wgj0qSDdJGlaCGGGScy4gnJmFbEE21HWdEWIp2SaRUkq2VAVgBvRdBMIAe60RkC/4mplxAvMGO8FcsAZGKz2qsbtXAMF8Xtf/ss1B790XPLIa5yT6vxT/SFkulkyCn4Tlz3ZnM9L8QyKVw/9Wac7RPHtrkMYmH7PPhiOGa/8OXXXtulxtGHhnfBcCihKKgRoVCCEM8p514h7yF7ya3kafKTMz97PgW1fCFfhDT6atoNRbAy+QKD3VCjPbpEVwI2JVGnAQiCKAUAHUEd2RUAqtdYPVOrU52mAI1doY6bilL9lE2lbni7my4kdU96BH/Yr1gdvrQ/bbi7wi634BP0oiJJvOQSORe4RS7jAhcP5Xa/V+ZCnogqu/olF6dwhpqIeWDlqJFU/H4u+GankOVC5uN/+S3PTNTtZyTB53cJgugPcHGXz8PJorvYk4ylQt6IN8r3+nmZxpfIwr7lSkAALkg1L5d3y1EZRCWTVkPBgE9w+QFC8c1KgeO96vR+AT/u5/XwALLgKRaT8Zk7JpZIwv7lodk7hqxUGHf0u5o7bgq1A+9lsZQ0wwbrJIkSuArtzoWEhGeqlxs0S0SnqlNew6IMllbW8UAtTURZWwGVWh8wQaDNVl2nWrkUoRkURYnNqFZQIEppLgAFqXyX1Q3QbXEvIrR/Ct0/FC8QeGNoO9ex7IeNT2/f5gHwbAOvIHmky2UOhPEtssfvgVHPY5IrsCPIyxhcDopJYYgDeaT9PLT13dbU/a1N3wWr7cdD0DUgjIqw+lV90GXfvRI8btjoFYXDkgc8LuFBj3yY3eS+CCdns7Ik8Nxhn++wIEh/t4vxRJ7Fk2VoizeR3eS6hbiSKVQlEYk+zpWynoZ6rc5C6Eh9JrNKekRE/XUsMp0eYIxyNIfNR/7ilDm4lRna4XDrp14Y4GRugHHLJwfE2hLBL/sO1JrcW9GWSqfLZUXTfhgGjyCPCjJw5wp+yRd2g1gcGjqVdUdDXPeAMCbAmlf1Ib7xO9/4QZfr4LhPFO+XveC55RYPeOX7fRtXYc9hWTZ7zIvXaWb4xgK2C5LIiddLOGEXeHnxxstIy7/u4584zsvaAjwUJC0vsSykzkx3/USjcHeGoZnhfnWcEVtdKDYOI+yLf6PqsbgnH9PjX1BoLOEpxPUELETfL1MviC4hkUK1oP4HIx90ucQ4NgQaYHpBCH+Im0A/1EZ6SB9ZS85jegGz/A6vNePAFZCjdTTK+UzQMYyC0owMNQxN0XRWamgCYebcXAoiIosf683gppLnr20YkQRAIsJNOtDllhqG5Ib1lz7w0GfdqvuT58lht/20W+ImJbdtJDQtwX4weWKe/dFWBOfEQjVuAndrTLZ2xd3tq46yIH7JL4dveV/Hu0TxfUsFEJ+DJ1jntdQURbObFfbrzrQoTvt2K2w1ndBprNbUj2/z6/gVTtwWIyb66Y1kC9k+22fxTgqiNBOREiajmlWlrSgEbQSeC8Yi6CPwg6wo5AtlFs9jyJ5nn8pKoExPOuH4Iu5qe180nY5yOZrON47C3qedwu6rQjWv6zklGArlng1xlFfSileIpNzhdD2ocjoftiIBIZYQlXRpt5XNZqs0nozHEwlMgdPRqT9E04CQu6LxIb7nV42H+d5f2Y9fuGx82Jf0+nzRgN+tibzoFr3t1OtPqgGvxy9xsuzyFDTgC2sK4/sTS+JOjnYyX3LImfl4Qq2CJVl1WuiV6sibuchbtTTmHwhEl+ZjsQ/SeTAez+fHtw0NbRsfP+0Z9WIsNXRWZ1TSAzCD/YijhnnUPJiedBBfyGYha9VoIhGPJRO/3rhu3XzIt9gdmWZnJLIosmp82kfNpGUR5r7LTo2OT6KEaRpTtLIWKbPEoXxa8XNSYWfcqpa1ALPAqLWluagb0eM6pdTvhWtn0vlSyIXWS9WQSk9Yau/3GmErnzeS8xB7WSwe0wRXIqjsbNHt8UeDwVQtJQhGeKXb07lq8WnPsESWL0D5LJWp600rU5JaD3oy0izay4xuVLd6jdbmorzi6IyeQJ1JJv47nD8nlztnjT9ejMWKgddCLt2lhaKURkO6oAtZmlNDimrF56F/+pBBO6ezc6grG6ykU9V0SPfrgWC6mlKUeJJGVmlRYDnabL3KkU5Sn//0m3KKPzxWp6T1skRZWlAvzEXjrs0jI1uvvmds1x1oPku1ZKE9US3NQwPKZzE8vj88XqutfUdf3zvWTscOp9O7wbPTu8jJbUfnzlDrHq5U85TmQiEmmb167xmo3DSM7NsXOQ2/TbKYVBfiN8NvJpfLC+B8Va9eutfKJkvVRHsBGf3W/Kgy1Kb53ELzFLtgYp44soB20F5E0SrQhb1PrVw7U/fjXrQoWklW/jOIjkZJq15BS8nhdC2kcpRzHE80ISkGje/OWifs4TzE3nzz+Lh8xm7nFJmblrh183OiXGeagf6nwE6qPFvmZsnkXLTHylCO67A4shj0/6ky0csqwaCSfWimTM5D63vfO34lXuOzZPH059uBdG05K+vHzptRKjmetiD8OWb/JON3W1sqmoK22CIsU9FFsOKE8feqcseZGP/jHu56vMb37Bk/je13n2LzqmSFc6bnzX+qMzSwdcK90yd8PNqwpNkWZg7SG6+njWhXMWpZ0WLXpxfDYhppV9ohcqyk+Zb4tJKpgf7J7qIZiRhBvz9ozE3054vF/qFKZah/164DF+N14EDG3D/a1zc6Uj6w0hv1OOH2LJrnoXMOfOe8P0bxJ+/d1orOFqOuVFGqGG9Xz68xAjKTmbX6GcK5xGlPYeFrTkK+WxhpH20fccppyErSsts/5n/DB4hCNJLAbKvdeQtknnh2hDKPOQt7YwImCoTJW5jJYCLTDQXM3lETnExFp3VM2WtMlzAykFimT1n+wiKJaqXO32TvHLP/nRoG5TnKUGxw3DONKvv90xh8vvMRbueGDTs5pzwoJZSoYUTjiiHqhqaFAu6MCAAZf1SNxXIxjju6GWlsXMa249ZR42X7JvjF7Zvs2PrLOO6y9c4+u/0KpBZjAqVS2RuMRFIRKeoNiKJPBaBZSlVRbMnP65hr+lv0tyiXpl+KKJX8DMo/Yl+82f4dctiI8kHEcOqP3AuNDvb7xWY4wn3jfBxoXMBQ5zZFjV/b74ZXPna+8+7pdf47eA/2fJJQZFwYOcbeEPB4K9y7ki+YBYu9i8GBQwqFsajCfV6JwhhQtfFh7mNJzf7o+je05HlpP+gqPK1SJEKxawi5zQM0BSMp2jgA36CpOeKJMbKN7JzfCp6s3bmW1ZNO8XflkxxeiZbomXm8juG15VQKs1tNL4Gq8SkXpWGPPyAl232xResiMS7Fx2I0HhbNrJt2pq27e2K0t2c4lc1nMrns3HbiqRvP/f4lSjYUDBphRZSSskv2SaFaKqjkaDjoV9wuj1cIVNpcidjF1e8/mN1gnS5eOeO8y5o37/r+RjO8NWxuLJuQ+Vp6bqR//1Sl8tTebdv2PvXUXDEgy1jOOZszq88+ityCyVd5zXAplerVI5rW+2IxRnt6htNWDvltQecVl16ampuAf7zh3L/fHsqFMCu5uPy9I9YGKxZbGt/6vblyr3eeZe51enGc7YSdHGRuN7wplUml02klCJ9aM1xOp3uZ9PVCuyakXG20zcrkgjFP/fzgonhPPBqNd+Xnpve3H85kzDZRtCL6h5jAIem+EHqxjrXtktgZ3+Tzp5LvTKZPc5YZ5EB54RyMTifO7MVLJ5jNJGwltJKw7tk8OJGDlefMwfROqkFn10DCyBjpjAntevfY4sVj5wfTS1OppRAKCwlXPNyWTKQicTEudrZ16eGI3jmP3P4ySjf3fOUgGOcYsU3lynkV6FL7c9nBLEihhKrkBrIRLZ1JRkdjyf/HPGzPu6+++sbP/HzPx79XKufXbMgvqefXr56biEZieWIw8dxXEs+tX7/zqrGxq3a+jTzshKB2w6l5WG6BnKY8vLaCVhGPCc3i77GRTpdohJnIxUOpoblJ+I+bNv5gh5ILxadh/OGH43+hPMxcAOe/HmwbfK7Yk101nKtUsmtWwdhg26q5Uf3X2JEjsTVrtl++cePl21n9tHH6erKJXLRg9jEjHp/hmfKn80y1GZ6pqVLaXCHrm1WopIcyq6A7zCdduqZ6fAExnvdGC6vDlEvyUarFVDGdkfX2lHnbYqp3Lx5qM7OGYWXmsfD33HP0qCeYUkOCFJfQJ4nBUhv4Q5auBn0hN+/2uvy9CXDFohf0Hr0PzGHz1lP5wmzHMnLBQpZjVgJTPqMEhnGJzmk6Qx1auKN9RTxltLUZqYPozhIZMNt6scwkeuFKVYi7opFoqi3t1+Tutf6s1qFrnbl54vnnqTba9cBdqYGU/gG8Hti//wFvMBFSrRUZUcjpwx5vLLqhDH/JPIaR3/tn5jG/Nc1YdymezcV6uw8VoRjTYJG6SHu1Sn19fr2a0YH+TU+vpWmZYCAQnEcQHqxWh8/t6zt3eDpvHc/n7mbPXFne6k/4mO0JOXH4Qb6GGpwgRTzxneR28gnyGfIA+RL5GnmMfIs8QZ4kGCxAmUpWEWievVe1Wq+4nT9gKbVCpZe9yEVH2pMGPQ0p6MOJKBv1Gnsxy76SmZGcADfFObF9rYDOFosaUFxgZbq5ajgiSuylA1aVSn0lbq7h7D7Q2M1ESWNvaMsYsKIcSYzLFCt153mAo44BDnMZ5G0BbwxOcuOInPNjSQ7FGrdF+5Hw5XT8NV78pqR77Xt09h5c5zIa8k876FblAM97pQd5FweXBzExAp6XH/d4OZ9sf9xS3UEI6G1+LhPSZQUstsj+Fi/xj31WDnnlZznB72m8LCk+d1BQJdjsjyQDn7Pv8GpyCCAka15494+HLhocvOhq2qVXA5JHFESP151Lu2WZEw3744ODGChU8TJYUeVT/xUMdnS6pZdkj6E12nXD0OFNtwouKaAeBXDJT/OeP4SedMl+j+clL8+5QJX1UKM9kNB9Abea2WBo+zV4BYn4heQNSo0n5JAQkH0hifu5JyDwjwXimvcJWQ7hrJAs3xsOnxNW1SuvzOWu5HivWw24+bCo8QDrLtVrVX2LVtUGdYLm/q17+Uf47ZjFuFBXAoSSKFrSDPrYLtSZGuknA6g1zLJuJheT7eQKsotcR/aQm8kthLA/e4Wt1gNekZ51Dd7GWr6Qd8SW/btslN8xdWhHO81Q/LafIeR+fpYLHvkZCgoo8s8kfvvUAL9HYZ30SwsDPnjGU+EDdwket/2y2yPcJYSI7uj0JN+DFi2MZ8P+r2GRAp5OEePBOunD8xkiw2QDGcET2ooZ2iUsRxNM1OCqiSYazJJONbO6EngnB8Xzaj0rwMCok6kW6uRZQa21nn9k6lAkAfwEJKbu4HdgdWoAEkl+AgF+7ImLBs7+6okqb7yhRPkdTWhP2pPcwNQhvqdnR88p144ezLdZAn4X93usJR1P10uWIE9GyFXkI+Qe8gXyZfJt8h3yDPk1+RNwEACUeGBW5eTXqZaZz1nsb3c1AVNrnSpVbKDLzzn/dcmHLZH9I49Hs1XGILqaL2QKVgq05qQC5t6tFi7GDa3W5myD5oOO2TOogwE9MZgvYh4vHB9PgTDjCcnMfmnmo5N6Kd385yxijHNM7FQqtX6wTqEOrbZgpqAN2KvgsPPksa/11PJEHV4t6uln0x0AHWnuY01ov5C2vytj3eIaYCW6wurmFRemO6ZewTG9vqPebdHVF7XXD2+9hfvfcJcgrLby3OEDz6zYXM5bo1ae//qtt36dh2u2re1aTfO3XPDQgcONrmZn3hqz2vnxa64Z57EMaYnV267pwNq1d/Pt1qq0XhSD14zDY9x1W87fw3F7zt9ynX2tAzinC4VsZHnfCMeN9C0fuf0OB4DTdWc0VPRnwtDhPCSijT0IDfrsqYTpRd1+mesKRiLBxs/+tFfyeqW9sscz4cFCZgV3X4lCh9F4Mb0IYFEankR4CXYESweS7cKqUfuDXz33QBEWLY3jQCf30UJpqGfEru9e2qntvvkHo6ug5/r+O54xivv/of/64qJdy257lOcfve2KQ7m2kR770ZHdmvHM55p9y3Z1ZrfXrh3nuPFrkSGg5g6NNVu17RboJQH48Qu3XMfzJ7hxvD6wnHHhOC+O1w8ppUDQoHZfK6DIIlRnk6OX6LMQCdwejMCoJ+j1Bj3NkvwfToKgEAAAeJxjYGRgYADiELPu8nh+m68M3CwMIHDd3PoLgv7fwMLA3ADkcjAwgUQBEtkJxwAAeJxjYGRgYG7438AQw8IAAkCSkQEV6AMARzUCmHicY2FgYGB+ycDAwjD0MADtEwGlAAAAAAB2AIoA8AFSAloCnALeA2QD2gUcBaYGTAaoBzYHwggICG4I6gluCcQKJgp6Cv4LagvoDGIMkA0CDYINtA3sDn4Oxg8sD6wQMhCIEOoRPhHKEkwSxhPgFLAVQBbueJxjYGRgYNBnlGaQYgABJiDmAkIGhv9gPgMAElIBfAB4nGWPTU7DMBCFX/oHpBKqqGCH5AViASj9EatuWFRq911036ZOmyqJI8et1ANwHo7ACTgC3IA78EgnmzaWx9+8eWNPANzgBx6O3y33kT1cMjtyDRe4F65TfxBukF+Em2jjVbhF/U3YxzOmwm10YXmD17hi9oR3YQ8dfAjXcI1P4Tr1L+EG+Vu4iTv8CrfQ8erCPuZeV7iNRy/2x1YvnF6p5UHFockikzm/gple75KFrdLqnGtbxCZTg6BfSVOdaVvdU+zXQ+ciFVmTqgmrOkmMyq3Z6tAFG+fyUa8XiR6EJuVYY/62xgKOcQWFJQ6MMUIYZIjK6Og7VWb0r7FDwl57Vj3N53RbFNT/c4UBAvTPXFO6stJ5Ok+BPV8bUnV0K27LnpQ0kV7NSRKyQl7WtlRC6gE2ZVeOEXpc0Yk/KGdI/wAJWm7IAAAAeJxtzVlPwkAUBeCe3ikg7gu47/uCyE8wVhuNxElooPo2odMyBmjDREB/vdNgwos3mZvMOTf5LNuaTNH6f6qwQWBwkEMeBcygiFnMYR4LWMQSlrGCVayhhDLWsYFNbGEbO9jFHvZxgEMc4RgnOMUZznGBS1zhGjeo4BZV3FkYs0h1JWsnoXSyVSuIQbujhnJQzIqK+ApVkou6phpQmLRJ9WJKw8iJukJ37F7qTC5UT8SyRqkObaGIu0/0wj1y3x7o8TUgzn3yA5+aDZfqnJPb8lhQv+fU8hr2e6M0kv1PJbL3reKkH4/NJy5P05GcxixJZZ8ZSJNQmhlKM2NpZjDNjGYy7mtmPM0MaIqWp52M0/TxzHNDFcqkRj8qzf8JlvUL5llXgA==
`

**Comment by AnaniZhu** [comment]
你项目里这个多出来的 Base64 字体可能有几种情况：

1. 项目内（或者第三方库）引入了 iconfont.css ，这个 css 里面引入 base64 字体
2. 项目内（或者第三方库）引入了字体文件，但该文件被 webpack url-loader 处理直接转成 base64 了

不过这个 iconfont 影响覆盖的确是个问题，这两天应该会发一个修复版，用  svg 替换所有图标。

**Comment by AnaniZhu** [comment]
v1.4.2 版本已修复，可以试试

**Comment by mercer08** [comment]
> v1.4.2 版本已修复，可以试试

发现两个问题
1. 在展示白色图片时，目前底部的操作栏背景色透明度太高，会导致操作按钮看不见，如下图，建议rgba的透明度调为0.5
![image](https://user-images.githubusercontent.com/12872293/87246189-4e7d9d80-c47e-11ea-9d13-f9c67b386cbc.png)
2. 再点击最小化按钮到不能点击时，再点击放大按钮，会报如下错误，并且点击放大按钮会失效，充值大小后，可以正常点击，不过缩到最小后，还是会出现此错误
`
vue.runtime.esm.js?0261:1888 TypeError: (t + e.innerScaleStep).toFixed is not a function
    at eval (index.js?66ff:1)
    at VueComponent.zoom (index.js?66ff:1)
    at VueComponent.increaseScale (index.js?66ff:1)
    at invokeWithErrorHandling (vue.runtime.esm.js?0261:1854)
    at Object.invoker [as click] (vue.runtime.esm.js?0261:2179)
    at VueComponent.handleClick (index.js?66ff:1)
    at invokeWithErrorHandling (vue.runtime.esm.js?0261:1854)
    at SVGSVGElement.invoker (vue.runtime.esm.js?0261:2179)
    at SVGSVGElement.original._wrapper (vue.runtime.esm.js?0261:6917)
`
--------------------
`
[Vue warn]: Error in v-on handler: "TypeError: (t + e.innerScaleStep).toFixed is not a function"

found in

 <SvgIcon>
       <ImagePreview>
         <ElCard> at packages/card/src/main.vue
           <OrderDetail> at src/views/modules/gz/order/OrderDetail.vue
             <ElTabPane> at packages/tabs/src/tab-pane.vue
               <ElTabs> at packages/tabs/src/tabs.vue
                 <MainContent> at src/views/layout/_common_center.vue
                   <Main> at src/views/main.vue
                     <App> at src/App.vue
                       <Root>`

**Comment by AnaniZhu** [comment]
> > v1.4.2 版本已修复，可以试试
> 
> 发现两个问题
> 
> 1. 在展示白色图片时，目前底部的操作栏背景色透明度太高，会导致操作按钮看不见，如下图，建议rgba的透明度调为0.5
>    ![image](https://user-images.githubusercontent.com/12872293/87246189-4e7d9d80-c47e-11ea-9d13-f9c67b386cbc.png)
> 2. 再点击最小化按钮到不能点击时，再点击放大按钮，会报如下错误，并且点击放大按钮会失效，充值大小后，可以正常点击，不过缩到最小后，还是会出现此错误
>    `vue.runtime.esm.js?0261:1888 TypeError: (t + e.innerScaleStep).toFixed is not a function at eval (index.js?66ff:1) at VueComponent.zoom (index.js?66ff:1) at VueComponent.increaseScale (index.js?66ff:1) at invokeWithErrorHandling (vue.runtime.esm.js?0261:1854) at Object.invoker [as click] (vue.runtime.esm.js?0261:2179) at VueComponent.handleClick (index.js?66ff:1) at invokeWithErrorHandling (vue.runtime.esm.js?0261:1854) at SVGSVGElement.invoker (vue.runtime.esm.js?0261:2179) at SVGSVGElement.original._wrapper (vue.runtime.esm.js?0261:6917)`
> 
> `
> [Vue warn]: Error in v-on handler: "TypeError: (t + e.innerScaleStep).toFixed is not a function"
> 
> found in
> 
> at packages/card/src/main.vue at src/views/modules/gz/order/OrderDetail.vue at packages/tabs/src/tab-pane.vue at packages/tabs/src/tabs.vue at src/views/layout/_common_center.vue at src/views/main.vue at src/App.vue `

第二点当传入字符串类型的 max-scale 和 min-scale 时, 缩放到临界点都有问题...

上面两个问题，v1.4.3 已发布修复

**Comment by mercer08** [comment]
> > > v1.4.2 版本已修复，可以试试
> > 
> > 
> > 发现两个问题
> > 
> > 1. 在展示白色图片时，目前底部的操作栏背景色透明度太高，会导致操作按钮看不见，如下图，建议rgba的透明度调为0.5
> >    ![image](https://user-images.githubusercontent.com/12872293/87246189-4e7d9d80-c47e-11ea-9d13-f9c67b386cbc.png)
> > 2. 再点击最小化按钮到不能点击时，再点击放大按钮，会报如下错误，并且点击放大按钮会失效，充值大小后，可以正常点击，不过缩到最小后，还是会出现此错误
> >    `vue.runtime.esm.js?0261:1888 TypeError: (t + e.innerScaleStep).toFixed is not a function at eval (index.js?66ff:1) at VueComponent.zoom (index.js?66ff:1) at VueComponent.increaseScale (index.js?66ff:1) at invokeWithErrorHandling (vue.runtime.esm.js?0261:1854) at Object.invoker [as click] (vue.runtime.esm.js?0261:2179) at VueComponent.handleClick (index.js?66ff:1) at invokeWithErrorHandling (vue.runtime.esm.js?0261:1854) at SVGSVGElement.invoker (vue.runtime.esm.js?0261:2179) at SVGSVGElement.original._wrapper (vue.runtime.esm.js?0261:6917)`
> > 
> > `
> > [Vue warn]: Error in v-on handler: "TypeError: (t + e.innerScaleStep).toFixed is not a function"
> > found in
> > at packages/card/src/main.vue at src/views/modules/gz/order/OrderDetail.vue at packages/tabs/src/tab-pane.vue at packages/tabs/src/tabs.vue at src/views/layout/_common_center.vue at src/views/main.vue at src/App.vue `
> 
> 第二点当传入字符串类型的 max-scale 和 min-scale 时, 缩放到临界点都有问题...
> 
> 上面两个问题，v1.4.3 已发布修复

问题已解决，感谢
