### ISSUE TITLE
图片放大后很模糊

### ISSUE THREAD

**Issue by mingtianyihou33** [AnaniZhu/vue-img-viewer#9]
我是使用了1.4M以上的图片，本来是很清晰的，但是使用本插件预览很模糊，放大后还是很模糊

**Comment by AnaniZhu** [comment]
方便发一下图片地址和代码吗？方便我定位下

**Comment by mingtianyihou33** [comment]
https://codesandbox.io/s/jovial-burnell-tfube?file=/src/App.vue
使用chrome可以复现，safari没有这个情况

**Comment by AnaniZhu** [comment]
在 chrome 上的确存在这个问题，定位到是 will-change 属性所影响。
v1.4.4 已修复。
